name: Reusable Workflow

on:
  push:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is a reusable workflow"
          echo caller workflow, ${{ inputs.env }}

