name: 워크플로우 테스트

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "배포할 환경을 선택하세요."
        required: true
        default: "development"
        type: choice
        options:
          - "production"
          - "development"

env:
  ENV: ${{ inputs.environment == 'production' && 'prod' || 'dev' }}

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        run: |
          echo "환경: ${{ env.ENV }}"
          echo "실행자: ${{ github.actor }}"
          echo "이메일: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
